### ISSUE TITLE
Webviewx from path which doesn't exist

### ISSUE THREAD

**Issue by engmsaleh** [kirit0-kun/flutter_paymob#2]
The project will not build as it depends on your local copy of Webviewx, I got the following issue, when I tried to run the code 
`Because flutter_paymob depends on webviewx from path which doesn't exist (could not find package webviewx at "../webviewx"), version solving failed.`

**Comment by mouEsam** [comment]
This issue was resolved. please give it another try.
Also try not to user `startPay`, `startPayActivityNoToken`, or `startPayActivityToken` as they depend on native plugins which are no longer supported and will be removed.
Also take a look at the manifest of the example project. in short you need to override `label` and `supportsRtl` in the application tag as such:
`tools:replace="android:label,android:supportsRtl"`
